### PR TITLE
Fixed documentation compliance for all methods

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #

fixed doc compliance for all methods

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Nice small fixes, thanks @Tom-Kingstone

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
