### PR TITLE
Upgrade to .NetStandard2.0

### LINKED ISSUE #59: Upgrade to .NetStandard2.0
In line with other toolkits close to the core.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #59

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 12019286319

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by adecler — APPROVED** [review]
- Code still compiles and copies the dlls across
 - The toolkit still works in GH ( based on the limited testing I have done)

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
