### PR TITLE
Initial code

### PR DESCRIPTION
**Pull request by adecler**
This is the initial code for defining the components of a BHoM abstract syntax tree and it's conversion to C# text.

This also provides a support for loops although more could be done on that to include loops that cover multiple components.

I will post an example in the comments below once I have created all relevant PRs. I do not provide this script on purpose 😋 . The key is to see if a script you write makes sense for you once it is in C#, (not just checking that my cluster works for you 😄 ).

Note that this also solves #1 .

I recommend to merge this independently of the PR in Grasshopper as this is initial code so bugs and lack of features are to be expected. I do however recommend to use this PR as a platform to raise issues before merging.

### CODE REVIEW

**Comment by adecler** [comment]
This GH script 

image

Gives us this C# code:

```
public static System.Object Test2(System.Double xStep, System.Double y, System.Double z)
{
     
    // Create nodes
    System.Collections.Generic.List<System.Double> series = BH.Engine.Data.Compute.Series(10, 0, xStep);
     
    //---- Create bottom node
    List<BH.oM.Geometry.Point> bottomPoints = series.Select(_x => BH.Engine.Geometry.Create.Point(_x, y)).ToList();
    List<BH.oM.Structure.Elements.Node> bottomNodes = bottomPoints.Select(_x => BH.Engine.Structure.Create.Node(_x, "bottom node")).ToList();
     
    //---- Create top node
    List<BH.oM.Geometry.Point> topPoints = series.Select(_x => new BH.oM.Geometry.Point{X = _x, Y = y, Z = z}).ToList();
    List<BH.oM.Structure.Elements.Node> topNodes = topPoints.Select(_x => new BH.oM.Structure.Elements.Node{Position = _x}).ToList();
     
    // Create the bars
    BH.oM.Structure.SectionProperties.SteelSection cHS = BH.Engine.Library.Query.Match("SectionProperties\\UK_SteelSections\\CHS", "CHS");
    List<BH.oM.Structure.Elements.Bar> bars = new List<BH.oM.Structure.Elements.Bar>();
    for (int _i = 0; _i < Math.Min(bottomNodes.Count(), topNodes.Count()); _i++)
        bars.Add(BH.Engine.Structure.Create.Bar(bottomNodes[_i], topNodes[_i], cHS, 0, null, BH.oM.Structure.Elements.BarFEAType.Axial));
     
    // Push the Bar through socket
    BH.Adapter.Socket.SocketAdapter adapter = new BH.Adapter.Socket.SocketAdapter();
    adapter.Push(bars);
     
    // Additional tests
     
    //---- Getting property
    List<System.String> json = bars.Select(_x => BH.Engine.Serialiser.Convert.ToJson(_x.StartNode)).ToList();
     
    //---- Explode
    List<BH.oM.Structure.Elements.Bar> flippedBars = new List<BH.oM.Structure.Elements.Bar>();
    for (int _i = 0; _i < Math.Min(bars.Count(), json.Count()); _i++)
        flippedBars.Add(BH.Engine.Structure.Create.Bar(bars[_i].EndNode, bars[_i].StartNode, null, 0, null, bars[_i].FEAType, json[_i]));
     
    //---- Setting property
    bars.ForEach(_x => _x.Name = "Test");
     
    //---- Inline type
    System.String s = BH.Engine.Reflection.Query.Description(typeof(BH.oM.Structure.Elements.Node));
     
    //---- Custom object
    List<System.Object> custom = new List<System.Object>();
    for (int _i = 0; _i < Math.Min(bars.Count(), flippedBars.Count()); _i++)
        custom.Add(new BH.oM.Base.CustomObject{CustomData = new System.Collections.Generic.Dictionary<System.String, System.Object>{{"x", s}, {"y", bars[_i]}, {"z", flippedBars[_i]}}});
     
    return custom;
}
```

**Comment by FraserGreenroyd** [comment]
@adecler I notice the GH PR depends on this PR which creates a slight dependency issue if the GH PR is merged because that's public org while this is currently private org - is that intentional? I understand from @al-fisher that we will eventually make this repo public but there'll be a period where we don't, and we probably don't want GH toolkit dependent on this private toolkit that people outside the public BHoM would not be able to access?

**Comment by rwemay** [comment]
That is pretty cool!

**Comment by adecler** [comment]
> @adecler I notice the GH PR depends on this PR which creates a slight dependency issue if the GH PR is merged because that's public org while this is currently private org - is that intentional? I understand from @al-fisher that we will eventually make this repo public but there'll be a period where we don't, and we probably don't want GH toolkit dependent on this private toolkit that people outside the public BHoM would not be able to access?

Damn! How did I not think of that?
Although there was an intention to have Node2Code private while we tweak it, the idea was very much to have it public as soon as it is ready. So I don't feel like having a private GH repo would be wise (even in a general context, I don't like the idea). @al-fisher , what do you think? Should we make node2code public straight away?

**Comment by al-fisher** [comment]
> Should we make node2code public straight away?

The short answer is yes! 👍 
Very happy with that - intention as you mention has always been to make public ASAP.
Also am very happy with WIP/experimental code being public in this instance too. As node2code is so foundational to the whole BHoM philosophy and the story around code and language we are telling

**Comment by adecler** [comment]
done :smile:

**Comment by al-fisher** [comment]
Started having a play with this! 
With my first comment being simply: 😍 
🤣 

In all seriousness - getting some pretty nice results actually! 
Although by just throwing some of my random, previously written scripts I had lying around, I did get some unexpected results. 
All minor actually so far - will continue to play - but raised a few issues to keep track.

None are super critical - have not prioritised or assigned to milestone. Raised all in Node2Code repo for ease of find-ability - although might make sense to transfer issues to Grasshopper (or other repo as appropriate after chatting next week on comments made here https://github.com/BHoM/Grasshopper_Toolkit/pull/447#issuecomment-571978811) 


See issues here: https://github.com/BHoM/Node2Code_Toolkit/issues/3 https://github.com/BHoM/Node2Code_Toolkit/issues/4 https://github.com/BHoM/Node2Code_Toolkit/issues/5 - I will continue to test!

Great stuff @adecler ! So good!

**Comment by adecler** [comment]
Closing this PR in favour of #9.

**Pull request closed without merging**
