### PR TITLE
Add ability to extract code from a method and to compile code into a method

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
Provide support for this UI PR:

   
### Issues addressed by this PR

Minimum set of features needed for the new RunCode component to work properly. More will come later on the same topic but this is the smallest possible amount of code to get the new component a valid prototype.

### Test files
Don't stress too much on the details for now. This is all new code and it will change. 
As long as the `RunCode` component works for simples cases, I am happy.  I mainly need this code out of my machine and in you hands so you can start playing with it. I will focus more seriously on it later this quarter when developing the prototype more seriously.

### CODE REVIEW

**Review by rolyhudson — APPROVED** [review]
See my notes [here](https://github.com/BHoM/BHoM_UI/pull/352#issuecomment-756271377) on the experience of using this handy prototype .

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Pull request merged**
